### PR TITLE
Update to Rust 2018

### PR DESCRIPTION
**Pull request by seanchen1991**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Realistically though I think the biggest update this crate needs is a notice saying it's no longer necessary! With rand 0.6 published on crates.io it now has native wasm-bindgen support. Perhaps the README could be updated with that?

**Comment by seanchen1991** [comment]
Oh cool, I didn't realize rand 0.6 now has native wasm-bindgen support. I'll need to go update my own wasm project. Yea, I'll update the README with a deprecation notice.

**Comment by seanchen1991** [comment]
Hopefully the formatting on the deprecation notice in the README is acceptable. Not sure what's kosher on that front.

**Comment by alexcrichton** [comment]
👍 

Looks great to me, thanks!

**Pull request merged**
